import json

import requests



def Order_status(properties,order_num):
    url = properties["url"] +  "api/foms/v2/order/status/webhook"

    payload={
                    "id": 216554,
                    "centre_id": 3,
                    "client_id": 87,
                    "logistics_provider_id": 12,
                    "pick_wave_id": 30725,
                    "status": "handovered",
                    "is_validation": 0,
                    "is_multi_items": 0,
                    "is_contain_temperature_control_items": 0,
                    "channel": "open_api",
                    "warehouse_service_code": "T1",
                    "order_number": order_num,
                    "shop_order_id": order_num,
                    "invoice_url": "https://th.timeswms.com/storage/invoices/577467120875964711_230621052854.pdf",
                    "datasource_provided_lastmile_info": "{\"label_url\": \"https://th.timeswms.com/storage/vas/THT0143BP9NG2Z230621010317.pdf\", \"tracking_number\": \"THT0143BP9NG2Z\"}",
                    "logistics_provider_account_id": 290,
                    "logistics_provider_service_detail": "{}",
                    "logistic_provider_code": "TIKTOK",
                    "logistic_provider_product": "TIKTOK",
                    "logistic_provider_account": "TIKTOK",
                    "consignee_name": "นาย วรากร ทองอุดร",
                    "consignee_phone": "(+66)0993335465",
                    "consignee_address": "นาย วรากรnเลขที่ 5/48 (Monaco3) nหมู่บ้าน - บ้านกลางเมือง nซ.ศรีนครินทร์24 nเขตสวนหลวง nแขวงสวนหลวง nจังหวั",
                    "consignee_country": "TH",
                    "upload_at": "2023-06-21 13:03:17",
                    "wave_assign_at": "2023-06-21 14:06:56",
                    "allocate_at": "2023-06-21 13:03:18",
                    "pack_at": "2023-06-21 17:28:54",
                    "handover_at": "2023-06-21 18:00:04",
                    "remarks": "577467120875964711",
                    "created_at": "2023-06-21 13:03:17",
                    "updated_at": "2023-06-21 18:00:04",
                    "consignee_province": "กรุงเทพมหานคร",
                    "consignee_city": "เขตสวนหลวง",
                    "consignee_postal_code": "10250",
                    "consignee_email": "577467120875964711@placeholder.com",
                    "shipper_name": "XUEWE",
                    "shipper_company": "XUEWE",
                    "shipper_phone": "13110910132",
                    "shipper_address": "No.515, Xuefu Road, XiaShaBaiYang Street, QianTang District，HangZhou City,ZheJiang Province",
                    "shipper_country": "CN",
                    "shipper_province": "Zhejiang",
                    "shipper_city": "Hangzhou",
                    "shipper_postal_code": "330100",
                    "shipper_email": "elepzhou98@163.com",
                    "order_value": 539.00,
                    "order_value_currency": "THB",
                    "payment_method": "PP",
                    "consignee_company": "นาย วรากร ทองอุดร",
                    "shipment_term": "DDP",
                    "other_charges_1": 0.00,
                    "other_charges_2": 0.00,
                    "other_charges_3": 0.00,
                    "is_partial_allocate_stock": 0,
                    "is_partial_pack": 0,
                    "status_text": "Handover",
                    "centre_code": "KECTH",
                    "client_code": "861048",
                    "number_of_package": 1,
                    "total_weight": 0.535,
                    "logistics_provider": {
                        "code": "TIKTOK",
                        "name": "TIKTOK"
                    },
                    "items": [
                        {
                            "id": 312129,
                            "order_id": 216554,
                            "shipment_id": 209070,
                            "sku_id": 495950,
                            "sku_name": "管道疏通液 500ml",
                            "requested_qty": 1,
                            "allocated_qty": 1,
                            "actual_qty": 1,
                            "second_sort_qty": 0,
                            "requested_uom": "EA",
                            "allocated_uom": "EA",
                            "pack_factor": 1,
                            "platform_name": "TIKTOK_CB_WH",
                            "platform_id": "5764640699668990725",
                            "allocate_at": "2023-06-21 13:03:18",
                            "pack_at": "2023-06-21 17:28:54",
                            "created_at": "2023-06-21 13:03:17",
                            "updated_at": "2023-06-21 17:28:54",
                            "unit_value_currency": "THB",
                            "unit_value": 539.00,
                            "manufacture_country_code": "CN",
                            "manufacture_country_name": "CN",
                            "line_item_id": "5764640699668990725",
                            "serial_numbers": "",
                            "condition": "GOOD",
                            "sku": "TESTTORI20230704001",
                            "sku_barcode": "40257982213"
                        }
                    ],
                    "stocks": [
                        {
                            "allocate_qty": 1,
                            "id": 659485,
                            "parent_id": 651558,
                            "last_updated_admin_id": 828,
                            "receive_by_admin_id": 8,
                            "centre_id": 3,
                            "client_id": 87,
                            "asn_id": 9089,
                            "asn_item_id": 403035,
                            "sku_id": 495950,
                            "order_id": 216554,
                            "order_item_id": 312129,
                            "bin_id": 7760,
                            "sku_barcode_id": 401746,
                            "condition": "GOOD",
                            "is_full_carton": 0,
                            "pack_factor": 1,
                            "receive_at": "2023-06-14 09:51:28",
                            "put_away_at": "2023-06-14 09:51:28",
                            "usable_at": "2023-06-14 09:55:08",
                            "allocate_at": "2023-06-21 13:03:18",
                            "pack_at": "2023-06-21 17:28:54",
                            "handover_at": "2023-06-21 18:00:04",
                            "created_at": "2023-06-21 13:03:18",
                            "updated_at": "2023-06-21 18:00:04"
                        }
                    ],
                    "shipments": [
                        {
                            "id": 209070,
                            "order_id": 216554,
                            "logistics_provider_id": 12,
                            "pallet_id": 28729,
                            "admin_id": 921,
                            "box_type_id": 23,
                            "is_temp_tracking_number": 0,
                            "tracking_number": order_num,
                            "temp_tracking_number": order_num,
                            "status": "handovered",
                            "logistics_provider_account_id": 290,
                            "logistics_provider_service_detail": "{}",
                            "consignee_name": "นาย วรากร ทองอุดร",
                            "consignee_company": "นาย วรากร ทองอุดร",
                            "consignee_phone": "(+66)0993335465",
                            "consignee_address": "นาย วรากรnเลขที่ 5/48 (Monaco3) nหมู่บ้าน - บ้านกลางเมือง nซ.ศรีนครินทร์24 nเขตสวนหลวง nแขวงสวนหลวง nจังหวั",
                            "consignee_country": "TH",
                            "consignee_province": "กรุงเทพมหานคร",
                            "consignee_city": "เขตสวนหลวง",
                            "consignee_postal_code": "10250",
                            "consignee_email": "577467120875964711@placeholder.com",
                            "shipper_name": "XUEWE",
                            "shipper_company": "XUEWE",
                            "shipper_phone": "13110910132",
                            "shipper_address": "No.515, Xuefu Road, XiaShaBaiYang Street, QianTang District，HangZhou City,ZheJiang Province",
                            "shipper_country": "CN",
                            "shipper_province": "Zhejiang",
                            "shipper_city": "Hangzhou",
                            "shipper_postal_code": "330100",
                            "shipper_email": "elepzhou98@163.com",
                            "parcel_value": 539.00,
                            "parcel_value_currency": "THB",
                            "actual_weight": 0.535,
                            "shipment_term": "DDP",
                            "documents": "[{\"url\":\"https:\/\/th.timeswms.com\/storage\/vas\/THT0143BP9NG2Z230621010317.pdf\",\"type\":\"LABEL\",\"qty\":1}]",
                            "local_label_url": "https://th.timeswms.com/storage/vas/THT0143BP9NG2Z230621010317.pdf",
                            "pack_at": "2023-06-21 17:28:54",
                            "photo_url": "",
                            "handover_at": "2023-06-21 18:00:04",
                            "ready_to_feedback_client_api": 1,
                            "feedback_client_api_attempts": 0,
                            "created_at": "2023-06-21 17:28:54",
                            "updated_at": "2023-06-21 18:00:04",
                            "status_text": "Handovered"
                        }
                    ]
                }


    headers = {
      'Authorization': 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJrZWNfaGtfb21zX3YyLjAiLCJ1c2VySWQiOjEsInVzZXJOYW1lIjoiYWRtaW4iLCJpYXQiOjE2Nzg3ODM3NTAsImV4cCI6MTY3OTM4ODU1MH0.M9_Jo5n9ZQGU0Atu1jAEnJabsHQi3mz7o3vfBThTNzw',
      'Content-Type': 'application/json'
    }

    response = requests.request("POST", url, headers = headers, data = json.dumps(payload))
    if "Success" in response.text:
        print("更新Order状态成功：")
    else:
        print(response.text)
