TWMS_URL = https://twms-th.kec-app.com

twms_username = TEST-PY

twms_password = Tc123456789%

client_name = TEST-PY

sku = CC0123

location = TEST-04

api_token = kf3kbChZGDRQXPPT4ZbRbGn8TA2YHKar51MTH4eoGCMy0a90WqlXbXWeOOPx

sku_data = sku_data.txt

asn_data = asn_data.txt

order_data = order_data.txt

centre_id = 4

centre_code = ITTEST

client_code = TEST-PY

box_type = ITST-01

agent =SELFPICK-PY

tote_code = TH1016

inbound_boxid_prefix = ITST