TWMS_URL = https://hm-cn-twms.kec-app.com

twms_username = TEST-PY

twms_password = Tc123456789%

client_name = TEST-PY

location = TEST0341

api_token = 7Rkx8TxXWdmNCiV50ChwARcgTFfZVEldfSSOjXuPzuIj2DS51tcmVvFPiN2h

sku_data = sku_data.txt

asn_data = asn_data.txt

order_data = order_data.txt

centre_code = ITTEST

client_code = TEST-PY

centre_id = 1

box_type = ITST-02

agent =SELFPICK-PY

tote_code = CN919



