TWMS_URL = https://twms-hk.kec-app.com/

twms_username = TEST-PY

twms_password = Tc123456789%

client_name = TEST-PY

sku = CC0123

location = A05029

api_token = s1QDasyvPyBGBIPznjCfNew3Ne77st23t1r78ODkLQZF04ZYVXZPtHom9GsC

sku_data = sku_data.txt

asn_data = asn_data.txt

order_data = order_data.txt

centre_id = 4

centre_code = DG

client_code = TEST-PY

box_type = TEST01

agent =SELFPICK-PY

tote_code = HK1016