TWMS_URL = https://qh-cn-twms.kec-app.com

twms_username = TEST-PY

twms_password = Tc123456789%

client_name = TEST-PY

sku = CC0123

location = QT0108

api_token = ZCZ3CnAxLhFhbGbZXITdHW8Mpk6dNlBTBmBTAA4tWpOd9JlB2gxcPj5fHw1y

sku_data = sku_data.txt

asn_data = asn_data.txt

order_data = order_data.txt

centre_id = 1

centre_code = ITSTWH

client_code = TEST-PY

box_type = TEST01

agent = SELFPICK-PY

tote_code = QH1016

inbound_boxid_prefix = DG